language: php

php:
  - 5.6

before_script:
  - composer install

script: phpunit --coverage-clover "clover" --configuration=phpunit.xml.dist

after_success:
    - curl -sL https://bit.ly/artifact-uploader | php

notifications:
  email:
    - nahuelcuestaluengo@gmail.com
